# This workflow builds and tests the Plankton iOS app.
name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: xcodebuild -project Plankton/Plankton.xcodeproj -scheme Plankton -destination 'generic/platform=iOS Simulator' -skipPackagePluginValidation build CODE_SIGNING_ALLOWED=NO

    - name: Run tests
      run: xcodebuild -project Plankton/Plankton.xcodeproj -scheme Plankton -destination 'platform=iOS Simulator,OS=latest,name=iPhone 17' -skipPackagePluginValidation test CODE_SIGNING_ALLOWED=NO
